### ISSUE TITLE
pretrained models

### ISSUE THREAD

**Issue by wuyuuu** [MouxiaoHuang/DUL#1]
Hi, 

First thanks for your great work.

I am wondering if you feel comfortable uploading pretrained models.

Looking forward to your reply.
Thanks

**Comment by MouxiaoHuang** [comment]
I trained from scratch and didn't use any pretrained models.
You could clone this repo and follow the instruction to train your own models. The training process is fast, which takes less than a day on Casia-WebFace dataset.

**Comment by MouxiaoHuang** [comment]
> Hi, 
> 
> 
> 
> First thanks for your great work.
> 
> 
> 
> I am wondering if you feel comfortable uploading pretrained models.
> 
> 
> 
> Looking forward to your reply.
> 
> Thanks

I trained from scratch and didn't use any pretrained models.
You could clone this repo and follow the instruction to train your own models. The training process is fast, which takes less than a day on Casia-WebFace dataset.

**Comment by wuyuuu** [comment]
> > Hi,
> > First thanks for your great work.
> > I am wondering if you feel comfortable uploading pretrained models.
> > Looking forward to your reply.
> > Thanks
> 
> I trained from scratch and didn't use any pretrained models. You could clone this repo and follow the instruction to train your own models. The training process is fast, which takes less than a day on Casia-WebFace dataset.

Get it, thanks for your answer 😄
